version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0


jobs:
  build_and_push:
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    steps:
      # Checkout the code as the first step.
      - checkout
      - setup_remote_docker
      - run:
          name: Build Details.
          command: |
            echo "Building Docker image using aws-ecr Orb commands."
            docker --version

      # These are commands within the ECR Orb.
      - aws-ecr/ecr_login:
          region: us-east-1

      - aws-ecr/build_image:
          region: us-east-1
          repo: gaiagps/elevation-service
          dockerfile: Dockerfile
          tag: ${CIRCLE_SHA1}


workflows:
  staging:
    jobs:
      - build_and_push