version: 2.1
orbs:
    aws-cli: circleci/aws-cli@5.1.0
    aws-ecr: circleci/aws-ecr@9.3.2

jobs:
    test:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            - aws-cli/setup
            - run:
                  name: Setup pnpm
                  command: sudo corepack enable && pnpm config set store-dir .pnpm-store
            - restore_cache:
                  name: Restore pnpm store
                  keys:
                      - pnpm-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Run tests
                  command: pnpm test:ci
            - save_cache:
                  name: Save pnpm store
                  key: pnpm-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - .pnpm-store

    ecr:
        docker:
            - image: cimg/base:current
        steps:
            - setup_remote_docker:
                  docker_layer_caching: true
            - aws-ecr/build_and_push_image:
                  auth:
                      - aws-cli/setup
                  repo: gaiagps/elevation-service
                  tag: ${CIRCLE_SHA1}

workflows:
    elevation:
        jobs:
            - test:
                  name: Unit tests
            - ecr:
                  name: ECR
                  requires:
                      - Unit tests
#                  filters:
#                      branches:
#                          only:
#                              - master
#                      tags:
