version: 2.1
orbs:
    aws-cli: circleci/aws-cli@5.1.0
    aws-ecr: circleci/aws-ecr@9.3.2

jobs:
    test:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            - aws-cli/setup
            - run:
                  name: Enable pnpm
                  command: sudo corepack enable
            - run:
                  name: Set pnpm store directory
                  command: pnpm config set store-dir .pnpm-store
            - restore_cache:
                  name: Restore pnpm store
                  keys:
                      - pnpm-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install dependencies
                  command: pnpm install
            - save_cache:
                  name: Save pnpm store
                  key: pnpm-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - .pnpm-store
            - run:
                  name: Build app
                  command: pnpm build
            - run:
                  name: Run tests
                  command: |
                      env PORT=5001 \
                      MAX_POST_SIZE=500000 \
                      MAX_LRU_SIZE=500000000 \
                      AWS_ELEVATION_BUCKET=com.gaiagps.dem \
                      TILE_DIRECTORY=elevation-server-data \
                      pnpm test

    ecr:
        docker:
            - image: cimg/base:current
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build Details.
                  command: |
                      echo "Building Docker image using aws-ecr Orb commands."
                      docker --version

            - aws-ecr/ecr_login:
                  region: us-east-1

            - aws-ecr/build_image:
                  region: us-east-1
                  repo: gaiagps/elevation-service
                  dockerfile: Dockerfile
                  tag: ${CIRCLE_SHA1}

workflows:
    elevation:
        jobs:
            - test:
                  name: Unit tests
            - ecr:
                  name: ECR
                  requires:
                      - Unit tests
